export enum Grade {
  Nursery = 'Nursery',
  KG1 = 'KG1',
  KG2 = 'KG2',
  Grade1 = '1',
  Grade2 = '2',
  Grade3 = '3',
  Grade4 = '4',
  Grade5 = '5',
  Grade6 = '6',
  Grade7 = '7',
  Grade8 = '8',
  Grade9 = '9',
  Grade10 = '10',
  Grade11 = '11',
  Grade12 = '12',
  University = 'University',
  Masters = 'Masters',
  Postgraduate = 'Postgraduate',
  Other = 'Other',
}
